[project]
name = "hands-on-editionv3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn>=1.6.1",
    "tensorflow>=2.18.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
